Archivos entregados: ventas_sucias_5000.csv
Enlace: https://drive.google.com/file/d/1_AHeM9tl6IsMbVme6a_7b9aD4Apu00je/view?usp=drive_link

Parte 1 — Exploración de datos (Pandas)
Actividades:

Cargar la base de datos

Mostrar:
• Primeras filas
• Información general del dataset
• Resumen estadístico

In [116]:

import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving ventas_sucias_5000.csv to ventas_sucias_5000 (5).csv

In [117]:
import pandas as pd
df = pd.read_csv('ventas_sucias_5000.csv')

df.info()
df.shape
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   object
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00

Parte 2 — Limpieza de datos (Pandas)

Realiza las siguientes tareas:
• Corregir tipos de datos incorrectos
• Identificar y manejar valores nulos
• Estandarizar columnas de texto:
• País
• Método de pago
• Revisar posibles valores atípicos (outliers)
• Corregir formatos de fecha si es necesario

In [118]:
#Correccion de datos incorrectos

df['pais'].unique()

array(['peru', 'chile', 'Colombia', 'Perú', 'COL', 'Chile', 'col'],
      dtype=object)

In [119]:
df['metodo_pago'].unique()

array(['Efectivo', 'Tarjeta', 'TRANSFERENCIA', 'transferencia'],
      dtype=object)

In [120]:
df['fecha'].unique()

array(['2024-01-01 00:00:00', '2024-01-01 01:00:00',
       '2024-01-01 02:00:00', ..., '2024-07-27 04:00:00',
       '2024-07-27 05:00:00', '2024-07-27 06:00:00'], dtype=object)

In [121]:
df['cantidad'].unique()

array([nan, '2', '9', '3', '6', '7', '1', '8', '5', '4', 'three'],
      dtype=object)

In [122]:
df['producto'].unique()

array(['Monitor', 'Laptop', 'Celular', 'Mouse', 'Teclado'], dtype=object)

In [123]:
df['precio'].unique()

array([1326.,   55., 1203., ..., 1788., 1019., 1672.])

In [124]:
#Manejo de valores nulos

from os import pardir

df ['precio'] = df ['precio'].replace('',None)
df ['cantidad'] = df ['cantidad'].replace(' ',None)

df["precio"] = df["precio"].fillna ("sin_informacion")
df["cantidad"] = df["cantidad"].fillna ("sin_informacion")

df.reset_index(drop=True)

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,sin_informacion,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00
...,...,...,...,...,...,...,...
4995,Juan,Laptop,1582.0,8,chile,transferencia,2024-07-27 03:00:00
4996,Carlos,Mouse,1553.0,2,Perú,Tarjeta,2024-07-27 04:00:00
4997,Juan,Monitor,1776.0,2,chile,Efectivo,2024-07-27 05:00:00
4998,Pedro,Laptop,1366.0,8,Chile,TRANSFERENCIA,2024-07-27 06:00:00
4999,Pedro,Mouse,406.0,1,chile,TRANSFERENCIA,2024-07-27 00:00:00

In [125]:
#Estandarizacion de columnas

#País

df["pais"] = df["pais"].replace(
{"COL" :"Colombia",
 "col":"Colombia",
 "peru":"Perú",
 "chile":"Chile",
})

#metodo de pago

df ["metodo_pago"] = df ["metodo_pago"].replace(
   {"TRANSFERENCIA" :"transferencia",
   })

In [126]:
df ["precio"] = pd.to_numeric(df["precio"], errors="coerce")
df ["cantidad"] = pd.to_numeric(df["cantidad"], errors="coerce")

In [127]:
#Valores atipicos

df = df [df["precio"]<10000]

In [128]:
df.reset_index(drop=True)

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,Perú,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2.0,Chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9.0,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3.0,Perú,transferencia,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6.0,Chile,Tarjeta,2024-01-01 04:00:00
...,...,...,...,...,...,...,...
4925,Juan,Laptop,1582.0,8.0,Chile,transferencia,2024-07-27 03:00:00
4926,Carlos,Mouse,1553.0,2.0,Perú,Tarjeta,2024-07-27 04:00:00
4927,Juan,Monitor,1776.0,2.0,Chile,Efectivo,2024-07-27 05:00:00
4928,Pedro,Laptop,1366.0,8.0,Chile,transferencia,2024-07-27 06:00:00
4929,Pedro,Mouse,406.0,1.0,Chile,transferencia,2024-07-27 00:00:00

Parte 3 — Análisis con Pandas
Actividades
• Crear una nueva columna llamada total: df['total'] = df['precio'] * df['cantidad']
Obtener:
• Total vendido
• Promedio de ventas
• Venta máxima
• Venta mínima

In [131]:
#Nueva columna

df["total"] = df["precio"] * df["cantidad"]
df.reset_index(drop=True)

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
0,Maria,Monitor,1326.0,NaN,Perú,Efectivo,2024-01-01 00:00:00,NaN
1,Luisa,Laptop,55.0,2.0,Chile,Tarjeta,2024-01-01 01:00:00,110.0
2,Carlos,Monitor,1203.0,9.0,Colombia,Efectivo,2024-01-01 02:00:00,10827.0
3,Luisa,Monitor,1304.0,3.0,Perú,transferencia,2024-01-01 03:00:00,3912.0
4,Luisa,Monitor,426.0,6.0,Chile,Tarjeta,2024-01-01 04:00:00,2556.0
...,...,...,...,...,...,...,...,...
4925,Juan,Laptop,1582.0,8.0,Chile,transferencia,2024-07-27 03:00:00,12656.0
4926,Carlos,Mouse,1553.0,2.0,Perú,Tarjeta,2024-07-27 04:00:00,3106.0
4927,Juan,Monitor,1776.0,2.0,Chile,Efectivo,2024-07-27 05:00:00,3552.0
4928,Pedro,Laptop,1366.0,8.0,Chile,transferencia,2024-07-27 06:00:00,10928.0
4929,Pedro,Mouse,406.0,1.0,Chile,transferencia,2024-07-27 00:00:00,406.0

In [184]:

print("Total vendido: ", f"${df['total'].sum():,.0f}".replace(",", "."))
print("Promedio de ventas: ", f"${df['total'].mean():,.0f}".replace(",", "."))
print("Venta máxima: ", f"${df['total'].max():,.0f}".replace(",", "."))
print("Venta mínima: ", f"${df['total'].min():,.0f}".replace(",", "."))

Total vendido:  $24.328.023
Promedio de ventas:  $5.034
Venta máxima:  $17.955
Venta mínima:  $10

Parte 4 — NumPy
Actividades
• Convertir columnas numéricas a un array de NumPy: data = df[['precio',
'cantidad']].to_numpy()
• Separar columnas utilizando indexación: precios = data[:, 0]
cantidades = data[:, 1]
• Aplicar vectorización para calcular ventas totales: totales = precios *
cantidades

In [169]:
import numpy as np

In [178]:
#Elimina de la tabla el registro que no tiene cantidad

df = df.dropna(subset= ["cantidad"])
df.reset_index(drop=True)

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
0,Luisa,Laptop,55.0,2.0,Chile,Tarjeta,2024-01-01 01:00:00,110.0
1,Carlos,Monitor,1203.0,9.0,Colombia,Efectivo,2024-01-01 02:00:00,10827.0
2,Luisa,Monitor,1304.0,3.0,Perú,transferencia,2024-01-01 03:00:00,3912.0
3,Luisa,Monitor,426.0,6.0,Chile,Tarjeta,2024-01-01 04:00:00,2556.0
4,Juan,Laptop,857.0,6.0,Colombia,transferencia,2024-01-01 05:00:00,5142.0
...,...,...,...,...,...,...,...,...
4828,Juan,Laptop,1582.0,8.0,Chile,transferencia,2024-07-27 03:00:00,12656.0
4829,Carlos,Mouse,1553.0,2.0,Perú,Tarjeta,2024-07-27 04:00:00,3106.0
4830,Juan,Monitor,1776.0,2.0,Chile,Efectivo,2024-07-27 05:00:00,3552.0
4831,Pedro,Laptop,1366.0,8.0,Chile,transferencia,2024-07-27 06:00:00,10928.0
4832,Pedro,Mouse,406.0,1.0,Chile,transferencia,2024-07-27 00:00:00,406.0

In [179]:
data = df[["precio", "cantidad"]].to_numpy()
print(data)

[[5.500e+01 2.000e+00]
 [1.203e+03 9.000e+00]
 [1.304e+03 3.000e+00]
 ...
 [1.776e+03 2.000e+00]
 [1.366e+03 8.000e+00]
 [4.060e+02 1.000e+00]]

In [180]:
precio = data[:,0]
cantidad = data[:,1]
print(precio)
print(cantidad)

[  55. 1203. 1304. ... 1776. 1366.  406.]
[2. 9. 3. ... 2. 8. 1.]

In [181]:
totales = precio * cantidad
print(totales)

[  110. 10827.  3912. ...  3552. 10928.   406.]

Parte 5 — Análisis con NumPy

Utilizando funciones de NumPy, calcular:
• Suma total de ventas
• Promedio de ventas
• Venta máxima
• Cantidad de ventas superiores a 1000

In [191]:

total_ventas = np.sum(totales)
print("Total de ventas:", f"${total_ventas:,.0f}".replace(",", "."))


promedio_ventas = np.mean(totales)
print("Promedio ventas:", f"{promedio_ventas:,.0f}".replace(",", "."))


venta_max = np.max(totales)
print("Venta máxima:", f"${venta_max:,.0f}".replace(",", "."))

cantidad_ventas = np.sum(totales > 1000)
print("Cantidad ventas > 1000:", f"{cantidad_ventas:,.0f}".replace(",","."))

Total de ventas: $24.328.023
Promedio ventas: 5.034
Venta máxima: $17.955
Cantidad ventas > 1000: 4.097

Parte 6 — Interpretación de resultados

Analiza y responde:
¿Los resultados obtenidos tienen sentido?: Me parece que al ser 4.834 registros y cada uno podria tener cantidades > 1 el valor recaudado es coherente, adiconando que el valor de los productos son bajos.

¿Detectaste valores sospechosos?: Si se identificaron valores nulos.

¿El promedio representa correctamente los datos?: Si, incluso si se divide el valor de las ventas sobre la cantidad de ventas mayores a >1.000 es casi el mismo resultado del promerio

¿Qué decisiones tomarías si esta fuera información real de negocio?: Compraria mas variedad de productos.